name: GitHub Action
on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build-steps
        run: echo "A demo build"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: tests-steps
        run: echo "A demo test"

