name: GitHub Action
on: workflow_dispatch
jobs:
  name:
    runs-on: ubuntu-latest
    steps:
      - name: Hello steps
        run: |
          echo "This is line one"
          echo "This is line two"
