name: Github Action Demo
on: push 
env:
  ENVIRONMENT_VAR : Saikat_D
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v5
      - name: run index.html file
        run: cat index.html
      - name: printing env
        run: echo "$ENVIRONMENT_VAR"
      - name: Show GitHub information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
